# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='id',
        ),
        migrations.AddField(
            model_name='mascota',
            name='folio',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False),
        ),
    ]
