# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0003_mascota_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('nombre', models.CharField(default='', max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='mascota',
            name='vacunas',
            field=models.ManyToManyField(to='mascota.Vacuna'),
        ),
    ]
