# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0004_auto_20171024_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='vacunas',
            field=models.ManyToManyField(blank=True, to='mascota.Vacuna'),
        ),
    ]
